### ISSUE TITLE
Lock runtime version

### ISSUE THREAD

**Issue by edwardshturman** [compsigh/web#99]
We had an issue with @nv-ram & @ashidtuguldur earlier where their Node.js environments locally were v25.x.x and `pnpm dev` failed with some `TypeError`:

```plaintext
localStorage.getItem() is not a function...
```

Locking it to the latest supported version with no issues (anecdotally seems to work with v20.19.2, but we can look for later versions) would help new devs get set up
